[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.1.0
    ESP32Async/AsyncTCP @ ^3.2.0
    bblanchon/ArduinoJson @ ^7.1.0
board_build.filesystem = littlefs
